//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InseroldProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musica
    {
        public int IDMusica { get; set; }
        public string TituloCancion { get; set; }
        public string Artista { get; set; }
        public string Disco { get; set; }
        public Nullable<System.DateTime> FechaProduccion { get; set; }
        public string Genero { get; set; }
        public Nullable<int> FKImagenMusica { get; set; }
    
        public virtual GaleriaMusica GaleriaMusica { get; set; }
    }
}
